apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a0kxgslut-go 
  janus-idp.io/tekton: a0kxgslut-go
  backstage.io/kubernetes-id: a0kxgslut-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a0kxgslut-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml